;;; typit-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (directory-file-name
                         (or (file-name-directory #$) (car load-path))))



;;; Generated autoloads from typit.el

(autoload 'typit-test "typit" "\
Run a typing test using the NUM most common words from the dictionary.

Dictionary is an array of words in `typit-dict'.  By default it's
English words ordered from most common to least common.

(fn NUM)" t)
(autoload 'typit-basic-test "typit" "\
Basic typing test (top 200 words).

See `typit-test' for more information." t)
(autoload 'typit-advanced-test "typit" "\
Advanced typing test (top 1000 words).

See `typit-test' for more information." t)
(register-definition-prefixes "typit" '("typit-"))

;;; End of scraped data

(provide 'typit-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; typit-autoloads.el ends here
